// Code generated by config-getters; DO NOT EDIT.

package config

import "io/fs"

// BaseConfig Getters

func (b BaseConfig) GetAuth() Auth {
	return b.Auth
}

func (b BaseConfig) GetPersistence() Persistence {
	return b.Persistence
}

func (b BaseConfig) GetViews() Views {
	return b.Views
}

// Auth Getters

func (a Auth) GetAudience() []string {
	return a.Audience
}

func (a Auth) GetAuthScheme() string {
	return a.AuthScheme
}

func (a Auth) GetContextKey() string {
	return a.ContextKey
}

func (a Auth) GetExtendedTokenDuration() int {
	return a.ExtendedTokenDuration
}

func (a Auth) GetIssuer() string {
	return a.Issuer
}

func (a Auth) GetRejectedRouteDefault() string {
	return a.RejectedRouteDefault
}

func (a Auth) GetRejectedRouteKey() string {
	return a.RejectedRouteKey
}

func (a Auth) GetSigningKey() string {
	return a.SigningKey
}

func (a Auth) GetSigningMethod() string {
	return a.SigningMethod
}

func (a Auth) GetTokenExpiration() int {
	return a.TokenExpiration
}

func (a Auth) GetTokenLookup() string {
	return a.TokenLookup
}

// Persistence Getters

func (p Persistence) GetDSN() string {
	return p.DSN
}

func (p Persistence) GetDebug() bool {
	return p.Debug
}

func (p Persistence) GetDriver() string {
	return p.Driver
}

func (p Persistence) GetOtelIdentifier() string {
	return p.OtelIdentifier
}

func (p Persistence) GetPingTimeoutExpression() string {
	return p.PingTimeoutExpression
}

func (p Persistence) GetServer() string {
	return p.Server
}

// Views Getters

func (v Views) GetAssetsDir() string {
	return v.AssetsDir
}

func (v Views) GetAssetsFS() fs.FS {
	return v.AssetsFS
}

func (v Views) GetCSSPath() string {
	return v.CSSPath
}

func (v Views) GetDebug() bool {
	return v.Debug
}

func (v Views) GetDevDir() string {
	return v.DevDir
}

func (v Views) GetDirFS() string {
	return v.DirFS
}

func (v Views) GetDirOS() string {
	return v.DirOS
}

func (v Views) GetEmbed() bool {
	return v.Embed
}

func (v Views) GetExt() string {
	return v.Ext
}

func (v Views) GetJSPath() string {
	return v.JSPath
}

func (v Views) GetReload() bool {
	return v.Reload
}

func (v Views) GetRemovePathPrefix() string {
	return v.RemovePathPrefix
}

func (v Views) GetTemplateFunctions() map[string]any {
	return v.TemplateFunctions
}

func (v Views) GetTemplatesFS() []fs.FS {
	return v.TemplatesFS
}
